name: Docker image

on:
  push:
    tags:
      - "v*" # triggers only if push new tag version, like `0.8.4` or else

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.21

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build image
      run: |
        make golib
        docker build --build-arg srv=MetaData --build-arg tag=${GITHUB_REF##*/} -t ghcr.io/chesscomputing/metadata ../golib/k8s

#     - name: Login to docker github registry
#       uses: docker/login-action@v1.6.0
#       with:
#         registry: docker.pkg.github.com
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}

#     - name: Publish image
#       uses: docker/build-push-action@v1
#       with:
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}
#         registry: docker.pkg.github.com
#         repository: vkuznet/dbs2go/dbs2go
#         tag_with_ref: true
